services:
  netbox:
    network_mode: host
    healthcheck:
      start_period: 90s    
  netbox-worker:
    network_mode: host
  netbox-housekeeping:
    network_mode: host
  postgres:
    network_mode: host
  redis:
    network_mode: host
  redis-cache:
    network_mode: host
